### ISSUE TITLE
cannot post query for upcoming launches

### ISSUE THREAD

**Issue by VenomFate-619** [r-spacex/SpaceX-API#856] opened 2021-07-18 08:59 UTC
posting data on this url
``` https://api.spacexdata.com/v4/launches/query```
with data

``` 
{
    "query": {
        "upcoming": true
    },
    "options": {
        "limit": 1,
        "select": {
            "name": 1,
            "id": 1,
            "date_local": 1,
            "flight_number": 1,
            "details": 1,
            "links": 1,
            "date_precision": 1
        },
        "sort": {
            "flight_number": "asc"
        },
        "populate": [
            {
                "path": "launchpad",
                "select": {
                    "name": 1,
                    "full_name": 1
                }
            },
            {
                "path": "rocket",
                "select": {
                    "name": 1,
                    "id": 1
                }
            }
        ]
    }
}

```

Getting response **Cannot read property 'map' of undefined**

**it was working few hours before the issue was raised, plz try to solve it fast as possible**

**Comment by VenomFate-619** [comment] 2021-07-18 09:04
You can verify by visiting this site 
https://x-info.eu/home
It was working few hours back as well yesterday also  and suddenly it is down .
See the console for errors

**Comment by shibilyt** [comment] 2021-07-18 09:09
Similar issue for me. 
I think the issue is with select. Because when I tried running queries without select, it's working fine.

**Comment by shibilyt** [comment] 2021-07-18 09:18
Interestingly, the old query works fine in the newly added v5. 

Instead of  `https://api.spacexdata.com/v4/launches/query`,
I used `https://api.spacexdata.com/v5/launches/query`

I just tested in postman.

**Comment by jakewmeyer** [comment] 2021-07-18 19:58
Should be fixed!

**Comment by Fedannie** [comment] 2021-07-18 20:48
@jakewmeyer Please, may you please review your fix once again? I'm getting a launch object inside a crew field. So now sometimes launch.crew is the same object as the launch. It seems to me this happens because of the 11th line in this document: routes/launches/v4/_transform-response.js

**Closed** 2021-11-13 15:12 UTC
Labels: Bug
